### ISSUE TITLE
ImportError: cannot import name downsample

### ISSUE THREAD

**Issue by learnmoremore** [uci-cbcl/DanQ#16]
when I run this model by "python DanQ_train.py",it comes a error,
Traceback (most recent call last):
  File "DanQ_train.py", line 8, in <module>
    from keras.models import Sequential
  File "build/bdist.linux-x86_64/egg/keras/models.py", line 15, in <module>
  File "build/bdist.linux-x86_64/egg/keras/utils/layer_utils.py", line 10, in <module>
  File "build/bdist.linux-x86_64/egg/keras/layers/convolutional.py", line 6, in <module>
ImportError: cannot import name downsample
what should I do?

**Comment by sukritikumar4** [comment]
I had the same issue. @learnmoremore were you able to find a solution through this?

**Comment by qijt123** [comment]
Hi,

I am currently working on a bioinformatics project involving non-coding DNA function and plan to benchmark the DanQ architecture.

I've successfully set up the Theano/Keras environment and downloaded the DeepSEA datasets. However, the official links to the pre-trained weights hosted on cbcl.ics.uci.edu are dead:

DanQ_bestmodel.hdf5
DanQ-JASPAR_bestmodel.hdf5
Does anyone in the community happen to have a backup of these .hdf5 files? If you could share a Google Drive, Dropbox, or Zenodo link, it would be a huge help for my research!

Thanks in advance!
